frappe.ui.form.on("Grey Fabric Issue", {
 setup(frm) {
  frm.set_query("flow_card", () => ({filters:{docstatus:1,production_status:["!=","已关闭"]}}));
  frm.set_query("batch_no", "items", (doc, cdt, cdn) => {const row=locals[cdt][cdn];return {query:"dyeing_finishing.dyeing_finishing.doctype.grey_fabric_issue.grey_fabric_issue.get_available_grey_fabric_batches",filters:{flow_card:frm.doc.flow_card,source_row:row.flow_card_grey_fabric_issue,exclude_batches:(frm.doc.items||[]).filter(item=>item.source_type==="自动带出"&&item.batch_no).map(item=>item.batch_no)}};});
 },
 refresh(frm) {frm.ignore_doctypes_on_cancel_all=["Stock Entry","Serial and Batch Bundle"];setDraftItemEditing(frm);loadPlanRows(frm);if (frm.is_new() || frm.doc.docstatus===0) frm.add_custom_button("新增补充批次",()=>addSupplement(frm),"胚布出库");},
 after_cancel(frm) {
  frappe.show_alert({message:"单据已恢复为草稿，可直接修改数量",indicator:"green"});
  frm.reload_doc();
 },
 flow_card(frm) {
  if (!frm.doc.flow_card) {frm.clear_table("items");frm.refresh_field("items");return;}
  frappe.call({method:"dyeing_finishing.dyeing_finishing.doctype.grey_fabric_issue.grey_fabric_issue.get_grey_fabric_issue_flow_card_details",args:{flow_card:frm.doc.flow_card},freeze:true,freeze_message:"正在带出流转卡胚布资料…",callback:({message})=>{
   if(!message)return;["sales_order","customer","customer_name","color_no","color","finished_product_name","finished_specification"].forEach(f=>frm.set_value(f,message[f]||""));frm._greyFabricPlans=message.plan_rows||[];frm.clear_table("items");(message.items||[]).forEach(data=>{const row=frm.add_child("items");Object.keys(data).forEach(f=>frappe.model.set_value(row.doctype,row.name,f,data[f]));});frm.refresh_field("items");setTotals(frm);
  }});
 }
});
frappe.ui.form.on("Grey Fabric Issue Item", {
 batch_no(frm,cdt,cdn) {const row=locals[cdt][cdn];if(!row.batch_no)return;frappe.call({method:"dyeing_finishing.dyeing_finishing.doctype.grey_fabric_issue.grey_fabric_issue.get_grey_fabric_issue_batch_details",args:{batch_no:row.batch_no,customer:frm.doc.customer,location:row.location||null},callback:({message})=>{if(!message)return;["item_code","grey_fabric_name","specification","color","stock_roll_count","stock_qty","warehouse","location"].forEach(f=>frappe.model.set_value(cdt,cdn,f,message[f]||""));assignPlanFromBatch(frm,cdt,cdn,message);}});},
 issue_roll_count(frm,cdt,cdn){setShortage(cdt,cdn);setTotals(frm);},
 issue_qty(frm,cdt,cdn){setShortage(cdt,cdn);setTotals(frm);},
 items_remove(frm){setTotals(frm);}
});
function addSupplement(frm) {const plans=frm._greyFabricPlans||[];if(!frm.doc.flow_card||!plans.length){frappe.msgprint("请先选择包含胚布领用计划的生产流转卡。");return;}const options=plans.map(p=>`${p.name}｜${p.grey_fabric_name||"未填写胚布"}｜${p.color||"无颜色"}`);frappe.prompt([{fieldname:"plan",label:"胚布领用计划",fieldtype:"Select",options:options.join("\n"),reqd:1}],values=>{const p=plans[options.indexOf(values.plan)],row=frm.add_child("items");["grey_fabric_name","color","planned_roll_count","planned_qty","warehouse","location"].forEach(f=>frappe.model.set_value(row.doctype,row.name,f,p[f]||""));frappe.model.set_value(row.doctype,row.name,"flow_card_grey_fabric_issue",p.name);frappe.model.set_value(row.doctype,row.name,"source_type","补充批次");frm.refresh_field("items");},"新增补充批次","确定");}
function setTotals(frm){const rows=frm.doc.items||[];frm.set_value("issue_roll_count",rows.reduce((total,row)=>total+flt(row.issue_roll_count),0));frm.set_value("issue_qty",rows.reduce((total,row)=>total+flt(row.issue_qty),0));}
function setShortage(cdt,cdn){const row=locals[cdt][cdn];frappe.model.set_value(cdt,cdn,"shortage_roll_count",Math.max(flt(row.planned_roll_count)-flt(row.issued_roll_count)-flt(row.issue_roll_count),0));frappe.model.set_value(cdt,cdn,"shortage_qty",Math.max(flt(row.planned_qty)-flt(row.issued_qty)-flt(row.issue_qty),0));}

function setIssueDefaults(frm,cdt,cdn){const row=locals[cdt][cdn];const others=(frm.doc.items||[]).filter(item=>item.name!==row.name&&item.flow_card_grey_fabric_issue===row.flow_card_grey_fabric_issue);const usedRolls=others.reduce((total,item)=>total+flt(item.issue_roll_count),0);const usedQty=others.reduce((total,item)=>total+flt(item.issue_qty),0);const remainingRolls=Math.max(flt(row.planned_roll_count)-flt(row.issued_roll_count)-usedRolls,0);const remainingQty=Math.max(flt(row.planned_qty)-flt(row.issued_qty)-usedQty,0);frappe.model.set_value(cdt,cdn,"issue_roll_count",Math.min(remainingRolls,flt(row.stock_roll_count)));frappe.model.set_value(cdt,cdn,"issue_qty",Math.min(remainingQty,flt(row.stock_qty)));}

function loadPlanRows(frm){if(!frm.doc.flow_card||frm._greyFabricPlans)return;frappe.call({method:"dyeing_finishing.dyeing_finishing.doctype.grey_fabric_issue.grey_fabric_issue.get_grey_fabric_issue_flow_card_details",args:{flow_card:frm.doc.flow_card},callback:({message})=>{frm._greyFabricPlans=(message&&message.plan_rows)||[];}});}
function assignPlanFromBatch(frm,cdt,cdn,detail){const row=locals[cdt][cdn];if(row.flow_card_grey_fabric_issue){setIssueDefaults(frm,cdt,cdn);setShortage(cdt,cdn);setTotals(frm);return;}const plans=(frm._greyFabricPlans||[]).filter(plan=>(!plan.grey_fabric_name||plan.grey_fabric_name===detail.grey_fabric_name)&&(!plan.color||!detail.color||plan.color.trim()===detail.color.trim())&&(!plan.location||plan.location===detail.location));if(!plans.length){frappe.msgprint("所选批次没有对应的流转卡胚布领用计划，不能出库。");frappe.model.set_value(cdt,cdn,"batch_no","");return;}const apply=plan=>{["grey_fabric_name","color","planned_roll_count","planned_qty","warehouse","location"].forEach(f=>frappe.model.set_value(cdt,cdn,f,plan[f]||""));frappe.model.set_value(cdt,cdn,"flow_card_grey_fabric_issue",plan.name);frappe.model.set_value(cdt,cdn,"source_type","补充批次");setIssueDefaults(frm,cdt,cdn);setShortage(cdt,cdn);setTotals(frm);};if(plans.length===1){apply(plans[0]);return;}const options=plans.map(plan=>`${plan.name}｜${plan.grey_fabric_name||"未填写胚布"}｜${plan.color||"无颜色"}`);frappe.prompt([{fieldname:"plan",label:"胚布领用计划",fieldtype:"Select",options:options.join("\n"),reqd:1}],values=>apply(plans[options.indexOf(values.plan)]),"选择胚布领用计划","确定");}
function setDraftItemEditing(frm){const grid=frm.fields_dict.items&&frm.fields_dict.items.grid;if(!grid)return;const editable=frm.doc.docstatus===0;["batch_no","issue_roll_count","issue_qty"].forEach(fieldname=>grid.update_docfield_property(fieldname,"read_only",editable?0:1));grid.refresh();}
